# 필요한 라이브러리 import

In [1]:
import pandas as pd
from data_concat import data_concat
from sentimentalAnalysis import sentimental_analysis
from sentimentalAnalysis import sentimental_analysis

## 2.1 ethereum-classic Train Data - Processed for Flair

- 전처리 이후 김도영 학우에게 전달하여 학습할 데이터
- 2022.04.13~2022.04.27

In [2]:
#tweet data 2022.04.14~2022.04.28
date="2022-04-"
d_concat = data_concat()
etc_df = []

for i in range(14,29):
    etc_df.append(pd.read_csv('./ethereum-classic/ETC OR ethereum classic_'+date+str(i), 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
    
etc_data = d_concat.concat(etc_df)

In [3]:
etc_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [4]:
etc_data= etc_data.dropna()
etc_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [5]:
# 데이터 저장
etc_data = etc_data.sort_values('date').reset_index(drop=True)
etc_data.to_csv('etc_train_data')
etc_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-12 21:40:37+00:00,1097488661699006464,The Bitcoin Street Journal,BTCstJournal,ETHUSD: Free Trading Signal ETHUSD: Free Tradi...,0,0,10721,1146
1,2022-04-12 21:47:50+00:00,15800847,Shulem Deen,shdeen,@dzkalman Thing is: it’s not like they don’t k...,0,3,4170,966
2,2022-04-12 23:02:43+00:00,1439350756293939204,Anthony W. Z.,ifitBleedsx4,@Stesspac @foofighters @FooFightersUK @foofigh...,0,1,916,989
3,2022-04-12 23:05:15+00:00,190915156,"NFTs Blockchain And SEO Developers, DM Coding ...",crypto_nftninja,Ethereum Classic has a bullish outlook for the...,0,1,1006,336
4,2022-04-12 23:38:55+00:00,374903677,Nick,Nickyy_Rozayy,I think this is a classic ESPN clickbait type ...,0,1,206,109
...,...,...,...,...,...,...,...,...,...
214,2022-04-27 22:18:45+00:00,1430923131636572166,Sam Sherman,Sherman_FFB,FFPC BB Classic (2017-2022): the top rookie WR...,0,0,169,311
215,2022-04-27 23:18:37+00:00,326110098,readCrypto,BbiKkuMi,Ethereum Classic (ETC) - April 28 - #ETCUSDT c...,0,0,583,144
216,2022-04-27 23:19:42+00:00,326110098,readCrypto,BbiKkuMi,Ethereum Classic (ETC) - 4월 28일 - #ETCUSDT 차트 ...,0,0,583,144
217,2022-04-27 23:27:10+00:00,1110640136159723520,Shatzeesmom,SharonD09506464,@CatDocMD Or the classic...tells EMS one story...,0,0,20,48
218,2022-04-27 23:49:52+00:00,637230109,LI Sports Fan,LIsportsfans,@Pia_Lemonade I grew up on what’s now called “...,0,4,1369,5004

In [6]:
flair_etc = etc_data[['date','tweet']]

In [7]:
sentimental_tweet = sentimental_analysis(flair_etc)

In [8]:
sentimental_tweet.process('flair')
flair_processed_etc = sentimental_tweet.twitter_data.drop('vader',axis=1)
flair_processed_etc

100%|███████████████████████████████████████| 219/219 [00:00<00:00, 8555.34it/s]

process time :  0.03744387626647949

,date,tweet,clean_text,flair
0,2022-04-12 21:40:37+00:00,ETHUSD: Free Trading Signal ETHUSD: Free Tradi...,ETHUSD Free Trading Signal ETHUSD Free Trading...,NaN
1,2022-04-12 21:47:50+00:00,@dzkalman Thing is: it’s not like they don’t k...,Thing is it is not like they do not know stand...,NaN
2,2022-04-12 23:02:43+00:00,@Stesspac @foofighters @FooFightersUK @foofigh...,_for_life Some classic Foo songs in thi,NaN
3,2022-04-12 23:05:15+00:00,Ethereum Classic has a bullish outlook for the...,Ethereum Classic has a bullish outlook for the...,NaN
4,2022-04-12 23:38:55+00:00,I think this is a classic ESPN clickbait type ...,I think this is a classic ESPN clickbait type ...,NaN
...,...,...,...,...
214,2022-04-27 22:18:45+00:00,FFPC BB Classic (2017-2022): the top rookie WR...,FFPC BB Classic ( 2017 2022 ) the top rookie W...,NaN
215,2022-04-27 23:18:37+00:00,Ethereum Classic (ETC) - April 28 - #ETCUSDT c...,Ethereum Classic ( ETC ) April 28 chart on,NaN
216,2022-04-27 23:19:42+00:00,Ethereum Classic (ETC) - 4월 28일 - #ETCUSDT 차트 ...,Ethereum Classic ( ETC ) 4 28,NaN
217,2022-04-27 23:27:10+00:00,@CatDocMD Or the classic...tells EMS one story...,Or the classic tells EMS one story ED nurse so...,NaN
218,2022-04-27 23:49:52+00:00,@Pia_Lemonade I grew up on what’s now called “...,_Lemonade I grew up on what is now called Clas...,NaN

In [9]:
flair_processed_etc.to_csv('flair_processed_etc_train_data')

In [10]:
pd.read_csv('flair_processed_etc_train_data').drop('Unnamed: 0',axis=1)

,date,tweet,clean_text,flair
0,2022-04-12 21:40:37+00:00,ETHUSD: Free Trading Signal ETHUSD: Free Tradi...,ETHUSD Free Trading Signal ETHUSD Free Trading...,NaN
1,2022-04-12 21:47:50+00:00,@dzkalman Thing is: it’s not like they don’t k...,Thing is it is not like they do not know stand...,NaN
2,2022-04-12 23:02:43+00:00,@Stesspac @foofighters @FooFightersUK @foofigh...,_for_life Some classic Foo songs in thi,NaN
3,2022-04-12 23:05:15+00:00,Ethereum Classic has a bullish outlook for the...,Ethereum Classic has a bullish outlook for the...,NaN
4,2022-04-12 23:38:55+00:00,I think this is a classic ESPN clickbait type ...,I think this is a classic ESPN clickbait type ...,NaN
...,...,...,...,...
214,2022-04-27 22:18:45+00:00,FFPC BB Classic (2017-2022): the top rookie WR...,FFPC BB Classic ( 2017 2022 ) the top rookie W...,NaN
215,2022-04-27 23:18:37+00:00,Ethereum Classic (ETC) - April 28 - #ETCUSDT c...,Ethereum Classic ( ETC ) April 28 chart on,NaN
216,2022-04-27 23:19:42+00:00,Ethereum Classic (ETC) - 4월 28일 - #ETCUSDT 차트 ...,Ethereum Classic ( ETC ) 4 28,NaN
217,2022-04-27 23:27:10+00:00,@CatDocMD Or the classic...tells EMS one story...,Or the classic tells EMS one story ED nurse so...,NaN
218,2022-04-27 23:49:52+00:00,@Pia_Lemonade I grew up on what’s now called “...,_Lemonade I grew up on what is now called Clas...,NaN

## 2.2 Vader, Textblob 감성분석 진행

- Textblob 감성 분석

In [11]:
sentimental_tweet.process('textblob')
sentimental_tweet.sentimental_with_textblob()

100%|██████████████████████████████████████| 219/219 [00:00<00:00, 11442.72it/s]

process time :  0.021138906478881836

100%|███████████████████████████████████████| 219/219 [00:00<00:00, 4301.81it/s]

textblob sentimental time :  0.05180811882019043

- Vader 감성 분석

In [12]:
sentimental_tweet.process('vader')
sentimental_tweet.sentimental_with_vader()

100%|██████████████████████████████████████| 219/219 [00:00<00:00, 10958.63it/s]

process time :  0.022572040557861328

100%|███████████████████████████████████████| 219/219 [00:00<00:00, 9945.03it/s]

vader sentimental time :  0.028836727142333984

In [13]:
sentimental_tweet.twitter_data = sentimental_tweet.twitter_data.drop('flair',axis=1)
sentimental_tweet.twitter_data

,date,tweet,clean_text,vader,textblob
0,2022-04-12 21:40:37+00:00,ETHUSD: Free Trading Signal ETHUSD: Free Tradi...,ETHUSD Free Trading Signal ETHUSD Free Trading...,0.7650,0.400000
1,2022-04-12 21:47:50+00:00,@dzkalman Thing is: it’s not like they don’t k...,Thing is it is not like they do not know stand...,-0.2755,0.000000
2,2022-04-12 23:02:43+00:00,@Stesspac @foofighters @FooFightersUK @foofigh...,_for_life Some classic Foo songs in thi,0.0000,0.166667
3,2022-04-12 23:05:15+00:00,Ethereum Classic has a bullish outlook for the...,Ethereum Classic has a bullish outlook for the...,0.0000,0.033333
4,2022-04-12 23:38:55+00:00,I think this is a classic ESPN clickbait type ...,I think this is a classic ESPN clickbait type ...,-0.2960,0.083333
...,...,...,...,...,...
214,2022-04-27 22:18:45+00:00,FFPC BB Classic (2017-2022): the top rookie WR...,FFPC BB Classic ( 2017 2022 ) the top rookie W...,0.2023,0.333333
215,2022-04-27 23:18:37+00:00,Ethereum Classic (ETC) - April 28 - #ETCUSDT c...,Ethereum Classic ( ETC ) April 28 chart on,0.0000,0.166667
216,2022-04-27 23:19:42+00:00,Ethereum Classic (ETC) - 4월 28일 - #ETCUSDT 차트 ...,Ethereum Classic ( ETC ) 4 28,0.0000,0.166667
217,2022-04-27 23:27:10+00:00,@CatDocMD Or the classic...tells EMS one story...,Or the classic tells EMS one story ED nurse so...,0.0000,0.083333
218,2022-04-27 23:49:52+00:00,@Pia_Lemonade I grew up on what’s now called “...,_Lemonade I grew up on what is now called Clas...,0.0000,0.166667

In [14]:
vader_textblob_etc_data = sentimental_tweet.twitter_data.sort_values('date').reset_index(drop=True)
vader_textblob_etc_data

,date,tweet,clean_text,vader,textblob
0,2022-04-12 21:40:37+00:00,ETHUSD: Free Trading Signal ETHUSD: Free Tradi...,ETHUSD Free Trading Signal ETHUSD Free Trading...,0.7650,0.400000
1,2022-04-12 21:47:50+00:00,@dzkalman Thing is: it’s not like they don’t k...,Thing is it is not like they do not know stand...,-0.2755,0.000000
2,2022-04-12 23:02:43+00:00,@Stesspac @foofighters @FooFightersUK @foofigh...,_for_life Some classic Foo songs in thi,0.0000,0.166667
3,2022-04-12 23:05:15+00:00,Ethereum Classic has a bullish outlook for the...,Ethereum Classic has a bullish outlook for the...,0.0000,0.033333
4,2022-04-12 23:38:55+00:00,I think this is a classic ESPN clickbait type ...,I think this is a classic ESPN clickbait type ...,-0.2960,0.083333
...,...,...,...,...,...
214,2022-04-27 22:18:45+00:00,FFPC BB Classic (2017-2022): the top rookie WR...,FFPC BB Classic ( 2017 2022 ) the top rookie W...,0.2023,0.333333
215,2022-04-27 23:18:37+00:00,Ethereum Classic (ETC) - April 28 - #ETCUSDT c...,Ethereum Classic ( ETC ) April 28 chart on,0.0000,0.166667
216,2022-04-27 23:19:42+00:00,Ethereum Classic (ETC) - 4월 28일 - #ETCUSDT 차트 ...,Ethereum Classic ( ETC ) 4 28,0.0000,0.166667
217,2022-04-27 23:27:10+00:00,@CatDocMD Or the classic...tells EMS one story...,Or the classic tells EMS one story ED nurse so...,0.0000,0.083333
218,2022-04-27 23:49:52+00:00,@Pia_Lemonade I grew up on what’s now called “...,_Lemonade I grew up on what is now called Clas...,0.0000,0.166667

In [15]:
vader_textblob_etc_data.to_csv('vader_textblob_etc_train_data')

## 2.1 ETC Test Data - Processed for Flair

- 2022.04.30~2022.05.14

In [16]:
#tweet data 2022.04.14~2022.04.28
date="2022-05-"
etc_test_df = []
d_concat = data_concat()

for i in range(1,16):
    day =''
    if i < 10 : 
        day='0'+str(i)
    else : 
        day = str(i)
    etc_test_df.append(pd.read_csv('./ethereum-classic/ETC OR ethereum classic_'+date+day, 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
etc_test_df.append(pd.read_csv('./ethereum-classic/ETC OR ethereum classic_2022-04-30', 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
etc_test_data = d_concat.concat(etc_test_df)
etc_test_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-30 23:58:16+00:00,3226845224,Fat Gandolf,silverdawg62,@katewitson1 @bob_wren Buy 100's of acres. Bui...,0,1,429,859
1,2022-04-30 20:24:58+00:00,1446844180102148098,GEM HODLERS News & Marketing Co.® 💎,TheGemHodlers,Ethereum Classic (ETC) Down 0.04% Saturday: Wh...,0,0,4634,259
2,2022-04-30 20:07:58+00:00,1471777236634456069,Perry,Perry_onn,Ethereum Classic (ETC) Down 0.04% Saturday: Wh...,0,0,20,3
3,2022-04-30 18:54:00+00:00,1470957049467088898,CheddarOats,CheddarOats,@ClassicRewards @ClassicPharaohs @ali22essa Th...,0,6,571,781
4,2022-04-30 18:49:05+00:00,1470957049467088898,CheddarOats,CheddarOats,@classic_greys Thank you so much for the givea...,0,10,571,781
...,...,...,...,...,...,...,...,...,...
775,2022-04-29 15:11:24+00:00,1331192609956655104,CoinRabbit,CoinRabbitLoans,added $ETC and enabled it on https://t.co/AtPX...,1,12,2230,915
776,2022-04-29 15:03:09+00:00,15966735,Florida Grand,florida_grand,"@TheOak97 Classic fascism. Yep, fascists total...",0,1,1248,1826
777,2022-04-29 14:55:55+00:00,1470816469063802881,Joshua,Yahemcheck,We are going to do some videos opening mystery...,0,1,1534,96
778,2022-04-29 07:15:51+00:00,1044925377188179969,mycrypto news,My_CryptoNews,Ethereum Classic [ETC] presents a good shortin...,0,0,296,134
779,2022-04-29 03:16:16+00:00,61221158,William Bunchuck,WBunchuck,@WFLA Even if you don’t consider separation of...,0,8,483,473

In [17]:
etc_test_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [18]:
etc_test_data =etc_test_data.dropna()
etc_test_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [19]:
# 데이터 저장
etc_test_data = etc_test_data.sort_values('date').reset_index(drop=True)
etc_test_data.to_csv('etc_test_data')
etc_test_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-28 12:56:45+00:00,1333449073840545800,lover,andriusjakimav2,@AltcoinGordon etc stands for ethereum classic...,0,1,28,106
1,2022-04-28 13:41:51+00:00,2326351885,XanderArt,XanderXCIV,@Abel36939839 @NextGenPlayer ITS NOT UNIQUE. I...,0,0,52,49
2,2022-04-28 16:22:25+00:00,617696585,Rob Palumbo 🇺🇦,RobPalumbo,The classic archetype of Shopify DTC operators...,1,3,592,1738
3,2022-04-28 17:14:37+00:00,387152939,Joe Corll,CupOfJoeCorll,@NikolasGlass I heard this morning there is go...,0,1,328,877
4,2022-04-28 17:29:21+00:00,1442716735606378500,Just A Guy,KryptoDick2021,@XRP_Productions Yeah people would be dumb to ...,0,1,93,155
...,...,...,...,...,...,...,...,...,...
775,2022-05-14 22:35:24+00:00,1356126318039973890,Safemoon-J🙏,JoseQtoMars,@Navohiky @MMCrypto Ethereum abandoned the ori...,0,4,999,1124
776,2022-05-14 23:41:37+00:00,2968136481,StikeDCmonMan 🤨,StikeDC,@AcademyMuseum @tcm @ProfJStewart @TheRealErne...,0,1,254,1106
777,2022-05-14 23:44:52+00:00,1351537380327641090,Kirito,uAdysqx,2. Olasılık muhtemelen önümüzdeki zamanda gerc...,0,0,76,321
778,2022-05-14 23:45:00+00:00,121748541,Josh Kessler,kessmoney,@peplau @ThatEricAlper Thank you. I think of ...,0,0,81,246
779,2022-05-14 23:51:07+00:00,1470957049467088898,CheddarOats,CheddarOats,@classic_greys @ETC_Frog @ThaKing1315 @realper...,0,3,631,910

In [20]:
flair_test_etc = etc_test_data[['date','tweet']]

In [21]:
sentimental_tweet = sentimental_analysis(flair_test_etc)

In [22]:
sentimental_tweet.process('flair')
flair_processed_etc_test = sentimental_tweet.twitter_data.drop('vader',axis=1)
flair_processed_etc_test

100%|██████████████████████████████████████| 780/780 [00:00<00:00, 12622.82it/s]

process time :  0.0648961067199707

,date,tweet,clean_text,flair
0,2022-04-28 12:56:45+00:00,@AltcoinGordon etc stands for ethereum classic...,etc stands for ethereum classic ok just went a...,NaN
1,2022-04-28 13:41:51+00:00,@Abel36939839 @NextGenPlayer ITS NOT UNIQUE. I...,ITS NOT UNIQUE Its from a bygone era Classic C...,NaN
2,2022-04-28 16:22:25+00:00,The classic archetype of Shopify DTC operators...,The classic archetype of Shopify DTC operators...,NaN
3,2022-04-28 17:14:37+00:00,@NikolasGlass I heard this morning there is go...,I heard this morning there is going to be ANOT...,NaN
4,2022-04-28 17:29:21+00:00,@XRP_Productions Yeah people would be dumb to ...,_Productions Yeah people would be dumb to do t...,NaN
...,...,...,...,...
775,2022-05-14 22:35:24+00:00,@Navohiky @MMCrypto Ethereum abandoned the ori...,Ethereum abandoned the original project called...,NaN
776,2022-05-14 23:41:37+00:00,@AcademyMuseum @tcm @ProfJStewart @TheRealErne...,Enjoyed the convo about influences of classic ...,NaN
777,2022-05-14 23:44:52+00:00,2. Olasılık muhtemelen önümüzdeki zamanda gerc...,2 Olaslk muhtemelen nmzdeki zamanda gerceklesi...,NaN
778,2022-05-14 23:45:00+00:00,@peplau @ThatEricAlper Thank you. I think of ...,Thank you I think of classic rock as a hard ro...,NaN
779,2022-05-14 23:51:07+00:00,@classic_greys @ETC_Frog @ThaKing1315 @realper...,_greys _Frog,NaN

In [23]:
flair_processed_etc_test.to_csv('flair_processed_etc_test_data')
pd.read_csv('flair_processed_etc_test_data').drop('Unnamed: 0',axis=1)

,date,tweet,clean_text,flair
0,2022-04-28 12:56:45+00:00,@AltcoinGordon etc stands for ethereum classic...,etc stands for ethereum classic ok just went a...,NaN
1,2022-04-28 13:41:51+00:00,@Abel36939839 @NextGenPlayer ITS NOT UNIQUE. I...,ITS NOT UNIQUE Its from a bygone era Classic C...,NaN
2,2022-04-28 16:22:25+00:00,The classic archetype of Shopify DTC operators...,The classic archetype of Shopify DTC operators...,NaN
3,2022-04-28 17:14:37+00:00,@NikolasGlass I heard this morning there is go...,I heard this morning there is going to be ANOT...,NaN
4,2022-04-28 17:29:21+00:00,@XRP_Productions Yeah people would be dumb to ...,_Productions Yeah people would be dumb to do t...,NaN
...,...,...,...,...
775,2022-05-14 22:35:24+00:00,@Navohiky @MMCrypto Ethereum abandoned the ori...,Ethereum abandoned the original project called...,NaN
776,2022-05-14 23:41:37+00:00,@AcademyMuseum @tcm @ProfJStewart @TheRealErne...,Enjoyed the convo about influences of classic ...,NaN
777,2022-05-14 23:44:52+00:00,2. Olasılık muhtemelen önümüzdeki zamanda gerc...,2 Olaslk muhtemelen nmzdeki zamanda gerceklesi...,NaN
778,2022-05-14 23:45:00+00:00,@peplau @ThatEricAlper Thank you. I think of ...,Thank you I think of classic rock as a hard ro...,NaN
779,2022-05-14 23:51:07+00:00,@classic_greys @ETC_Frog @ThaKing1315 @realper...,_greys _Frog,NaN

## 2.2 Vader, Textblob 감성분석 진행

- Vader 감성 분석

In [24]:
sentimental_tweet.process('vader')
sentimental_tweet.sentimental_with_vader()

100%|██████████████████████████████████████| 780/780 [00:00<00:00, 12284.59it/s]

process time :  0.06562423706054688

100%|██████████████████████████████████████| 780/780 [00:00<00:00, 10183.17it/s]

vader sentimental time :  0.08094215393066406

- Textblob 감성 분석

In [25]:
sentimental_tweet.process('textblob')
sentimental_tweet.sentimental_with_textblob()

100%|██████████████████████████████████████| 780/780 [00:00<00:00, 12599.97it/s]

process time :  0.06412386894226074

100%|███████████████████████████████████████| 780/780 [00:00<00:00, 9997.27it/s]

textblob sentimental time :  0.07880878448486328

In [26]:
sentimental_tweet.twitter_data = sentimental_tweet.twitter_data.drop('flair',axis=1)
sentimental_tweet.twitter_data

,date,tweet,clean_text,vader,textblob
0,2022-04-28 12:56:45+00:00,@AltcoinGordon etc stands for ethereum classic...,etc stands for ethereum classic ok just went a...,0.2960,0.333333
1,2022-04-28 13:41:51+00:00,@Abel36939839 @NextGenPlayer ITS NOT UNIQUE. I...,its not unique its from a bygone era classic c...,-0.3182,-0.010417
2,2022-04-28 16:22:25+00:00,The classic archetype of Shopify DTC operators...,the classic archetype of shopify dtc operators...,0.3818,0.166667
3,2022-04-28 17:14:37+00:00,@NikolasGlass I heard this morning there is go...,i heard this morning there is going to be anot...,-0.5574,0.000000
4,2022-04-28 17:29:21+00:00,@XRP_Productions Yeah people would be dumb to ...,_productions yeah people would be dumb to do t...,0.4588,-0.036111
...,...,...,...,...,...
775,2022-05-14 22:35:24+00:00,@Navohiky @MMCrypto Ethereum abandoned the ori...,ethereum abandoned the original project called...,-0.1779,0.270833
776,2022-05-14 23:41:37+00:00,@AcademyMuseum @tcm @ProfJStewart @TheRealErne...,enjoyed the convo about influences of classic ...,0.7003,0.333333
777,2022-05-14 23:44:52+00:00,2. Olasılık muhtemelen önümüzdeki zamanda gerc...,2 olaslk muhtemelen nmzdeki zamanda gerceklesi...,0.0000,0.166667
778,2022-05-14 23:45:00+00:00,@peplau @ThatEricAlper Thank you. I think of ...,thank you i think of classic rock as a hard ro...,0.2732,-0.062500
779,2022-05-14 23:51:07+00:00,@classic_greys @ETC_Frog @ThaKing1315 @realper...,_greys _frog,0.0000,0.000000

In [27]:
vader_textblob_etc_test_data = sentimental_tweet.twitter_data
vader_textblob_etc_test_data.to_csv('vader_textblob_etc_test_data')
pd.read_csv('vader_textblob_etc_test_data')

,Unnamed: 0,date,tweet,clean_text,vader,textblob
0,0,2022-04-28 12:56:45+00:00,@AltcoinGordon etc stands for ethereum classic...,etc stands for ethereum classic ok just went a...,0.2960,0.333333
1,1,2022-04-28 13:41:51+00:00,@Abel36939839 @NextGenPlayer ITS NOT UNIQUE. I...,its not unique its from a bygone era classic c...,-0.3182,-0.010417
2,2,2022-04-28 16:22:25+00:00,The classic archetype of Shopify DTC operators...,the classic archetype of shopify dtc operators...,0.3818,0.166667
3,3,2022-04-28 17:14:37+00:00,@NikolasGlass I heard this morning there is go...,i heard this morning there is going to be anot...,-0.5574,0.000000
4,4,2022-04-28 17:29:21+00:00,@XRP_Productions Yeah people would be dumb to ...,_productions yeah people would be dumb to do t...,0.4588,-0.036111
...,...,...,...,...,...,...
775,775,2022-05-14 22:35:24+00:00,@Navohiky @MMCrypto Ethereum abandoned the ori...,ethereum abandoned the original project called...,-0.1779,0.270833
776,776,2022-05-14 23:41:37+00:00,@AcademyMuseum @tcm @ProfJStewart @TheRealErne...,enjoyed the convo about influences of classic ...,0.7003,0.333333
777,777,2022-05-14 23:44:52+00:00,2. Olasılık muhtemelen önümüzdeki zamanda gerc...,2 olaslk muhtemelen nmzdeki zamanda gerceklesi...,0.0000,0.166667
778,778,2022-05-14 23:45:00+00:00,@peplau @ThatEricAlper Thank you. I think of ...,thank you i think of classic rock as a hard ro...,0.2732,-0.062500
779,779,2022-05-14 23:51:07+00:00,@classic_greys @ETC_Frog @ThaKing1315 @realper...,_greys _frog,0.0000,0.000000