# ÌïÑÏöîÌïú ÎùºÏù¥Î∏åÎü¨Î¶¨ import

In [1]:
import matplotlib.pyplot as plt
import tqdm
import pandas as pd
import csv

from data_concat import data_concat
from sentimentalAnalysis import sentimental_analysis
from coincrawler import coin_crawl_his
from data_pipeline import coin_data_pipeline
from sentimentalAnalysis import sentimental_analysis

## 2.1 Coin Train Data - Processed for Flair

- Ï†ÑÏ≤òÎ¶¨ Ïù¥ÌõÑ ÍπÄÎèÑÏòÅ ÌïôÏö∞ÏóêÍ≤å Ï†ÑÎã¨ÌïòÏó¨ ÌïôÏäµÌï† Îç∞Ïù¥ÌÑ∞
- 2022.04.13~2022.04.27

In [2]:
#tweet data 2022.04.14~2022.04.28
date="2022-04-"
d_concat = data_concat()
coin_df = []

for i in range(14,29):
    coin_df.append(pd.read_csv('./coin_crypto/crypto OR coin_'+date+str(i), 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))

coin_data = d_concat.concat(coin_df)

In [3]:
coin_data.isna().sum()

date                0
user_id             0
user_name           1
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [4]:
coin_data= coin_data.dropna()
coin_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [5]:
# Îç∞Ïù¥ÌÑ∞ Ï†ÄÏû•
coin_data = coin_data.sort_values('date').reset_index(drop=True)
coin_data.to_csv('coin_train_data')
coin_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-13 03:18:35+00:00,1492786230647480324,n4s_crypto,n4s_crypto,@CitadelDAO @cheqd_io üî•üî•üî•üî•üî•üî•üî•üî•üî•\nDone :) \n@Ma...,0,0,50,462
1,2022-04-13 03:20:49+00:00,1158548215,Shawn Dall,Chronamut,@WAX_io #WAX @CEOofNFTs @Crypto33Miggy @Chrona...,0,2,2347,1581
2,2022-04-13 03:21:01+00:00,565334865,Lorena Armenta,fly2k777,Under pressure from local financial regulators...,0,0,11,95
3,2022-04-13 03:22:33+00:00,1092770259680014336,‚¨° 2NthaLink1NthaStink ‚¨°,lukeste99990409,@Tyler_DO0d My fear is that even in the midst ...,0,1,1003,516
4,2022-04-13 03:22:33+00:00,1506092071479746563,Roi MoneyBags,roimoneybags,My takeaway is that even the sharks believe cr...,0,0,23,71
...,...,...,...,...,...,...,...,...,...
128904,2022-04-27 23:59:40+00:00,1456781805613367296,Tenny‚öíÔ∏è,tennyb_CC,@Crypto_Hamilton @NeckerVentures @Nisha020782,0,1,348,1394
128905,2022-04-27 23:59:49+00:00,1513814273801310208,Dusty Field,dusty_field,@JustinD59013407 @MattWallace888 Ummm multiply...,0,5,12,73
128906,2022-04-27 23:59:52+00:00,21268897,Josh Marshall,joshtpm,"fascinating story, just no end of corruption ....",21,61,376740,811
128907,2022-04-27 23:59:52+00:00,4704538075,EverGreenCoin¬Æ (EGC) üå≤,EverGreenCoin_,"Another beautiful day! It's April 27, 2022 at ...",2,3,7082,613
128908,2022-04-27 23:59:58+00:00,1482354025135804417,Denver,Denver_btc,@crypto_123456 Keep hodling.,0,0,38,170

In [6]:
flair_coin = coin_data[['date','tweet']]

In [7]:
sentimental_tweet = sentimental_analysis(flair_coin)

In [8]:
sentimental_tweet.process('flair')
flair_processed_coin = sentimental_tweet.twitter_data.drop('vader',axis=1)
flair_processed_coin

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 128909/128909 [00:07<00:00, 16412.15it/s]

process time :  7.942216157913208

,date,tweet,clean_text,flair
0,2022-04-13 03:18:35+00:00,@CitadelDAO @cheqd_io üî•üî•üî•üî•üî•üî•üî•üî•üî•\nDone :) \n@Ma...,_io Done ) _witt,NaN
1,2022-04-13 03:20:49+00:00,@WAX_io #WAX @CEOofNFTs @Crypto33Miggy @Chrona...,_io _Crypto,NaN
2,2022-04-13 03:21:01+00:00,Under pressure from local financial regulators...,Under pressure from local financial regulators...,NaN
3,2022-04-13 03:22:33+00:00,@Tyler_DO0d My fear is that even in the midst ...,_DO0d My fear is that even in the midst of Def...,NaN
4,2022-04-13 03:22:33+00:00,My takeaway is that even the sharks believe cr...,My takeaway is that even the sharks believe cr...,NaN
...,...,...,...,...
128904,2022-04-27 23:59:40+00:00,@Crypto_Hamilton @NeckerVentures @Nisha020782,_Hamilton,NaN
128905,2022-04-27 23:59:49+00:00,@JustinD59013407 @MattWallace888 Ummm multiply...,Umm multiply coins in circulation x price per ...,NaN
128906,2022-04-27 23:59:52+00:00,"fascinating story, just no end of corruption ....",fascinating story just no end of corruption Le...,NaN
128907,2022-04-27 23:59:52+00:00,"Another beautiful day! It's April 27, 2022 at ...",Another beautiful day It's April 27 2022 at 07...,NaN
128908,2022-04-27 23:59:58+00:00,@crypto_123456 Keep hodling.,_123456 Keep hodling,NaN

In [9]:
flair_processed_coin.to_csv('flair_processed_coin_train_data')

In [11]:
pd.read_csv('flair_processed_coin_train_data',lineterminator='\n').drop('Unnamed: 0',axis=1)

,date,tweet,clean_text,flair
0,2022-04-13 03:18:35+00:00,@CitadelDAO @cheqd_io üî•üî•üî•üî•üî•üî•üî•üî•üî•\nDone :) \n@Ma...,_io Done ) _witt,NaN
1,2022-04-13 03:20:49+00:00,@WAX_io #WAX @CEOofNFTs @Crypto33Miggy @Chrona...,_io _Crypto,NaN
2,2022-04-13 03:21:01+00:00,Under pressure from local financial regulators...,Under pressure from local financial regulators...,NaN
3,2022-04-13 03:22:33+00:00,@Tyler_DO0d My fear is that even in the midst ...,_DO0d My fear is that even in the midst of Def...,NaN
4,2022-04-13 03:22:33+00:00,My takeaway is that even the sharks believe cr...,My takeaway is that even the sharks believe cr...,NaN
...,...,...,...,...
128904,2022-04-27 23:59:40+00:00,@Crypto_Hamilton @NeckerVentures @Nisha020782,_Hamilton,NaN
128905,2022-04-27 23:59:49+00:00,@JustinD59013407 @MattWallace888 Ummm multiply...,Umm multiply coins in circulation x price per ...,NaN
128906,2022-04-27 23:59:52+00:00,"fascinating story, just no end of corruption ....",fascinating story just no end of corruption Le...,NaN
128907,2022-04-27 23:59:52+00:00,"Another beautiful day! It's April 27, 2022 at ...",Another beautiful day It's April 27 2022 at 07...,NaN
128908,2022-04-27 23:59:58+00:00,@crypto_123456 Keep hodling.,_123456 Keep hodling,NaN

## 2.2 Vader, Textblob Í∞êÏÑ±Î∂ÑÏÑù ÏßÑÌñâ

- Textblob Í∞êÏÑ± Î∂ÑÏÑù

In [12]:
sentimental_tweet.process('textblob')
sentimental_tweet.sentimental_with_textblob()

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 128909/128909 [00:07<00:00, 16426.41it/s]

process time :  7.928130865097046

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 128909/128909 [00:11<00:00, 11412.26it/s]

textblob sentimental time :  11.29654598236084

- Vader Í∞êÏÑ± Î∂ÑÏÑù

In [13]:
sentimental_tweet.process('vader')
sentimental_tweet.sentimental_with_vader()

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 128909/128909 [00:07<00:00, 16218.83it/s]

process time :  7.999913930892944

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 128909/128909 [00:09<00:00, 13877.90it/s]

vader sentimental time :  9.296015977859497

In [14]:
sentimental_tweet.twitter_data = sentimental_tweet.twitter_data.drop('flair',axis=1)
sentimental_tweet.twitter_data

,date,tweet,clean_text,vader,textblob
0,2022-04-13 03:18:35+00:00,@CitadelDAO @cheqd_io üî•üî•üî•üî•üî•üî•üî•üî•üî•\nDone :) \n@Ma...,_io Done ) _witt,0.0000,0.000000
1,2022-04-13 03:20:49+00:00,@WAX_io #WAX @CEOofNFTs @Crypto33Miggy @Chrona...,_io _Crypto,0.0000,0.000000
2,2022-04-13 03:21:01+00:00,Under pressure from local financial regulators...,Under pressure from local financial regulators...,-0.6486,0.000000
3,2022-04-13 03:22:33+00:00,@Tyler_DO0d My fear is that even in the midst ...,_DO0d My fear is that even in the midst of Def...,-0.4939,0.000000
4,2022-04-13 03:22:33+00:00,My takeaway is that even the sharks believe cr...,My takeaway is that even the sharks believe cr...,0.4404,0.233333
...,...,...,...,...,...
128904,2022-04-27 23:59:40+00:00,@Crypto_Hamilton @NeckerVentures @Nisha020782,_Hamilton,0.0000,0.000000
128905,2022-04-27 23:59:49+00:00,@JustinD59013407 @MattWallace888 Ummm multiply...,Umm multiply coins in circulation x price per ...,0.0000,0.000000
128906,2022-04-27 23:59:52+00:00,"fascinating story, just no end of corruption ....",fascinating story just no end of corruption Le...,0.6249,0.700000
128907,2022-04-27 23:59:52+00:00,"Another beautiful day! It's April 27, 2022 at ...",Another beautiful day It's April 27 2022 at 07...,0.7351,0.850000
128908,2022-04-27 23:59:58+00:00,@crypto_123456 Keep hodling.,_123456 Keep hodling,0.0000,0.000000

In [15]:
vader_textblob_coin_data = sentimental_tweet.twitter_data.sort_values('date').reset_index(drop=True)
vader_textblob_coin_data

,date,tweet,clean_text,vader,textblob
0,2022-04-13 03:18:35+00:00,@CitadelDAO @cheqd_io üî•üî•üî•üî•üî•üî•üî•üî•üî•\nDone :) \n@Ma...,_io Done ) _witt,0.0000,0.000000
1,2022-04-13 03:20:49+00:00,@WAX_io #WAX @CEOofNFTs @Crypto33Miggy @Chrona...,_io _Crypto,0.0000,0.000000
2,2022-04-13 03:21:01+00:00,Under pressure from local financial regulators...,Under pressure from local financial regulators...,-0.6486,0.000000
3,2022-04-13 03:22:33+00:00,@Tyler_DO0d My fear is that even in the midst ...,_DO0d My fear is that even in the midst of Def...,-0.4939,0.000000
4,2022-04-13 03:22:33+00:00,My takeaway is that even the sharks believe cr...,My takeaway is that even the sharks believe cr...,0.4404,0.233333
...,...,...,...,...,...
128904,2022-04-27 23:59:40+00:00,@Crypto_Hamilton @NeckerVentures @Nisha020782,_Hamilton,0.0000,0.000000
128905,2022-04-27 23:59:49+00:00,@JustinD59013407 @MattWallace888 Ummm multiply...,Umm multiply coins in circulation x price per ...,0.0000,0.000000
128906,2022-04-27 23:59:52+00:00,"fascinating story, just no end of corruption ....",fascinating story just no end of corruption Le...,0.6249,0.700000
128907,2022-04-27 23:59:52+00:00,"Another beautiful day! It's April 27, 2022 at ...",Another beautiful day It's April 27 2022 at 07...,0.7351,0.850000
128908,2022-04-27 23:59:58+00:00,@crypto_123456 Keep hodling.,_123456 Keep hodling,0.0000,0.000000

In [16]:
vader_textblob_coin_data.to_csv('vader_textblob_coin_train_data')

## 2.1 COIN Test Data - Processed for Flair

- 2022.04.30~2022.05.14

In [18]:
#tweet data 2022.04.14~2022.04.28
date="2022-05-"
coin_test_df = []
d_concat = data_concat()

for i in range(1,12):
    day =''
    if i < 10 : 
        day='0'+str(i)
    else : 
        day = str(i)
    coin_test_df.append(pd.read_csv('./coin_crypto/crypto OR coin_'+date+day, 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
for i in range(12,16):
    coin_test_df.append(pd.read_csv('./coin_crypto/coin_'+date+str(i), 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
    coin_test_df.append(pd.read_csv('./coin_crypto/crypto_'+date+str(i), 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))

coin_test_df.append(pd.read_csv('./coin_crypto/crypto OR coin_2022-04-30', 
                                  encoding='utf-8', on_bad_lines='skip').drop('number',axis=1))
coin_test_data = d_concat.concat(coin_test_df)
coin_test_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-30 23:59:49+00:00,4704538075,EverGreenCoin¬Æ (EGC) üå≤,EverGreenCoin_,"Another beautiful day! It's April 30, 2022 at ...",2,4,7090,608
1,2022-04-30 23:59:44+00:00,840690747749851136,Algonese,Algorand_OG,@uormatthews Weve been waiting for crypto regu...,0,0,868,877
2,2022-04-30 23:59:14+00:00,1505715027902357504,Christian Brooks,christi25100822,#dccomic #spawn #michaeljaiwhite #johnleguizam...,2,2,48,406
3,2022-04-30 23:59:01+00:00,1358506337508941827,Claw,CEOFortKnocks,#Crypto #tonic #cro #staking \nHow low will it...,6,11,247,169
4,2022-04-30 23:58:43+00:00,824324406507933696,Angela J,GenWealthMama,@The_Crypto_Wiz @BeliveinCrypto @_SkyToken üôè‚ù£Ô∏è,0,3,1928,3766
...,...,...,...,...,...,...,...,...,...
280479,2022-04-29 02:55:38+00:00,1181590684362395650,Crypto&NFT&Metaverse NEWS,additionalrules,NFT news.\n\nStaking NFT coin GMT on Bybit for...,0,0,1204,5
280480,2022-04-29 02:55:13+00:00,1487131927530381317,ArtFormed,art_formed,Check out GRUMPY CLAM #4 by Art Formed at http...,1,3,2,3
280481,2022-04-29 02:54:10+00:00,1500540155547037702,Ramon 4 U.S.A.,ramon4usa,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,0,0,13,12
280482,2022-04-29 02:54:09+00:00,1183794864275640320,GeminiTourist.eth,GeminiTourist,"tired of logins, try #Web3 authentication thro...",1,0,361,4782
280483,2022-04-29 02:53:40+00:00,1227324771894886400,nollied,nolliechain,@BenWest that‚Äôs pretty cool you got them into ...,0,0,184,410

In [19]:
coin_test_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [20]:
coin_test_data = coin_test_data.dropna()
coin_test_data.isna().sum()

date                0
user_id             0
user_name           0
user_screen_name    0
tweet               0
retweets            0
likes               0
follower_number     0
following_number    0
dtype: int64

In [21]:
# Îç∞Ïù¥ÌÑ∞ Ï†ÄÏû•
coin_test_data = coin_test_data.sort_values('date').reset_index(drop=True)
coin_test_data.to_csv('coin_test_data')
coin_test_data

,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number
0,2022-04-29 02:53:40+00:00,1227324771894886400,nollied,nolliechain,@BenWest that‚Äôs pretty cool you got them into ...,0,0,184,410
1,2022-04-29 02:54:09+00:00,1183794864275640320,GeminiTourist.eth,GeminiTourist,"tired of logins, try #Web3 authentication thro...",1,0,361,4782
2,2022-04-29 02:54:10+00:00,1500540155547037702,Ramon 4 U.S.A.,ramon4usa,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,0,0,13,12
3,2022-04-29 02:55:13+00:00,1487131927530381317,ArtFormed,art_formed,Check out GRUMPY CLAM #4 by Art Formed at http...,1,3,2,3
4,2022-04-29 02:55:38+00:00,1181590684362395650,Crypto&NFT&Metaverse NEWS,additionalrules,NFT news.\n\nStaking NFT coin GMT on Bybit for...,0,0,1204,5
...,...,...,...,...,...,...,...,...,...
280479,2022-05-14 23:59:13+00:00,1144353561490468865,Todd 4 Freedom üôèüèª,Tcraw444,@NicoleArbour since the only people who ‚Äúunder...,0,1,244,164
280480,2022-05-14 23:59:13+00:00,1460935876641492998,Ric Caruso,Ric4PAGuv,@Z_Humphries Sharing my thoughts about those f...,0,0,103,715
280481,2022-05-14 23:59:37+00:00,26120252,Sal,satoshisdead,Just another reason to stay away from coinbase...,0,1,8900,3536
280482,2022-05-14 23:59:46+00:00,4704538075,EverGreenCoin¬Æ (EGC) üå≤,EverGreenCoin_,Another beautiful day! Please vote for $EGC ev...,3,7,7092,622
280483,date,user_id,user_name,user_screen_name,tweet,retweets,likes,follower_number,following_number

In [22]:
flair_test_coin = coin_test_data[['date','tweet']]

In [23]:
sentimental_tweet = sentimental_analysis(flair_test_coin)

In [24]:
sentimental_tweet.process('flair')
flair_processed_coin_test = sentimental_tweet.twitter_data.drop('vader',axis=1)
flair_processed_coin_test

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 280484/280484 [00:18<00:00, 15563.70it/s]

process time :  18.232107162475586

,date,tweet,clean_text,flair
0,2022-04-29 02:53:40+00:00,@BenWest that‚Äôs pretty cool you got them into ...,that is pretty cool you got them into crypto a...,NaN
1,2022-04-29 02:54:09+00:00,"tired of logins, try #Web3 authentication thro...",tired of logins try authentication through a w...,NaN
2,2022-04-29 02:54:10+00:00,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,_crypto 3/3 which I infer that you are also ag...,NaN
3,2022-04-29 02:55:13+00:00,Check out GRUMPY CLAM #4 by Art Formed at http...,Check out GRUMPY CLAM by Art Formed at NFT via,NaN
4,2022-04-29 02:55:38+00:00,NFT news.\n\nStaking NFT coin GMT on Bybit for...,NFT news Staking NFT coin GMT on Bybit for 99 ...,NaN
...,...,...,...,...
280479,2022-05-14 23:59:13+00:00,@NicoleArbour since the only people who ‚Äúunder...,since the only people who understand it seem t...,NaN
280480,2022-05-14 23:59:13+00:00,@Z_Humphries Sharing my thoughts about those f...,_Humphries Sharing my thoughts about those few...,NaN
280481,2022-05-14 23:59:37+00:00,Just another reason to stay away from coinbase...,Just another reason to stay away from coinbase...,NaN
280482,2022-05-14 23:59:46+00:00,Another beautiful day! Please vote for $EGC ev...,Another beautiful day Please vote for $ EGC ev...,NaN
280483,date,tweet,tweet,NaN

In [25]:
flair_processed_coin_test.to_csv('flair_processed_coin_test_data')
pd.read_csv('flair_processed_coin_test_data',lineterminator='\n').drop('Unnamed: 0',axis=1)

,date,tweet,clean_text,flair
0,2022-04-29 02:53:40+00:00,@BenWest that‚Äôs pretty cool you got them into ...,that is pretty cool you got them into crypto a...,NaN
1,2022-04-29 02:54:09+00:00,"tired of logins, try #Web3 authentication thro...",tired of logins try authentication through a w...,NaN
2,2022-04-29 02:54:10+00:00,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,_crypto 3/3 which I infer that you are also ag...,NaN
3,2022-04-29 02:55:13+00:00,Check out GRUMPY CLAM #4 by Art Formed at http...,Check out GRUMPY CLAM by Art Formed at NFT via,NaN
4,2022-04-29 02:55:38+00:00,NFT news.\n\nStaking NFT coin GMT on Bybit for...,NFT news Staking NFT coin GMT on Bybit for 99 ...,NaN
...,...,...,...,...
280479,2022-05-14 23:59:13+00:00,@NicoleArbour since the only people who ‚Äúunder...,since the only people who understand it seem t...,NaN
280480,2022-05-14 23:59:13+00:00,@Z_Humphries Sharing my thoughts about those f...,_Humphries Sharing my thoughts about those few...,NaN
280481,2022-05-14 23:59:37+00:00,Just another reason to stay away from coinbase...,Just another reason to stay away from coinbase...,NaN
280482,2022-05-14 23:59:46+00:00,Another beautiful day! Please vote for $EGC ev...,Another beautiful day Please vote for $ EGC ev...,NaN
280483,date,tweet,tweet,NaN

## 2.2 Vader, Textblob Í∞êÏÑ±Î∂ÑÏÑù ÏßÑÌñâ

- Vader Í∞êÏÑ± Î∂ÑÏÑù

In [26]:
sentimental_tweet.process('vader')
sentimental_tweet.sentimental_with_vader()

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 280484/280484 [00:18<00:00, 15522.10it/s]

process time :  18.207806825637817

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 280484/280484 [00:22<00:00, 12717.84it/s]

vader sentimental time :  22.0588321685791

- Textblob Í∞êÏÑ± Î∂ÑÏÑù

In [27]:
sentimental_tweet.process('textblob')
sentimental_tweet.sentimental_with_textblob()

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 280484/280484 [00:18<00:00, 14774.71it/s]

process time :  19.106769800186157

100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 280484/280484 [00:26<00:00, 10616.78it/s]

textblob sentimental time :  26.419776916503906

In [28]:
sentimental_tweet.twitter_data = sentimental_tweet.twitter_data.drop('flair',axis=1)
sentimental_tweet.twitter_data

,date,tweet,clean_text,vader,textblob
0,2022-04-29 02:53:40+00:00,@BenWest that‚Äôs pretty cool you got them into ...,that is pretty cool you got them into crypto a...,0.8126,0.433333
1,2022-04-29 02:54:09+00:00,"tired of logins, try #Web3 authentication thro...",tired of logins try authentication through a w...,-0.4404,-0.400000
2,2022-04-29 02:54:10+00:00,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,_crypto 3/3 which i infer that you are also ag...,0.0000,0.000000
3,2022-04-29 02:55:13+00:00,Check out GRUMPY CLAM #4 by Art Formed at http...,check out grumpy clam by art formed at nft via,0.0000,0.000000
4,2022-04-29 02:55:38+00:00,NFT news.\n\nStaking NFT coin GMT on Bybit for...,nft news staking nft coin gmt on bybit for 99 ...,0.0000,0.000000
...,...,...,...,...,...
280479,2022-05-14 23:59:13+00:00,@NicoleArbour since the only people who ‚Äúunder...,since the only people who understand it seem t...,0.5859,0.000000
280480,2022-05-14 23:59:13+00:00,@Z_Humphries Sharing my thoughts about those f...,_humphries sharing my thoughts about those few...,0.6369,0.150000
280481,2022-05-14 23:59:37+00:00,Just another reason to stay away from coinbase...,just another reason to stay away from coinbase...,-0.3400,0.000000
280482,2022-05-14 23:59:46+00:00,Another beautiful day! Please vote for $EGC ev...,another beautiful day please vote for $ egc ev...,0.7351,0.850000
280483,date,tweet,tweet,0.0000,0.000000

In [29]:
vader_textblob_coin_test_data = sentimental_tweet.twitter_data
vader_textblob_coin_test_data.to_csv('vader_textblob_coin_test_data')
pd.read_csv('vader_textblob_coin_test_data',lineterminator='\n')

,Unnamed: 0,date,tweet,clean_text,vader,textblob
0,0,2022-04-29 02:53:40+00:00,@BenWest that‚Äôs pretty cool you got them into ...,that is pretty cool you got them into crypto a...,0.8126,0.433333
1,1,2022-04-29 02:54:09+00:00,"tired of logins, try #Web3 authentication thro...",tired of logins try authentication through a w...,-0.4404,-0.400000
2,2,2022-04-29 02:54:10+00:00,@AdamMB79 @RyanSIMs101 @5starduds @geezer_cryp...,_crypto 3/3 which i infer that you are also ag...,0.0000,0.000000
3,3,2022-04-29 02:55:13+00:00,Check out GRUMPY CLAM #4 by Art Formed at http...,check out grumpy clam by art formed at nft via,0.0000,0.000000
4,4,2022-04-29 02:55:38+00:00,NFT news.\n\nStaking NFT coin GMT on Bybit for...,nft news staking nft coin gmt on bybit for 99 ...,0.0000,0.000000
...,...,...,...,...,...,...
280479,280479,2022-05-14 23:59:13+00:00,@NicoleArbour since the only people who ‚Äúunder...,since the only people who understand it seem t...,0.5859,0.000000
280480,280480,2022-05-14 23:59:13+00:00,@Z_Humphries Sharing my thoughts about those f...,_humphries sharing my thoughts about those few...,0.6369,0.150000
280481,280481,2022-05-14 23:59:37+00:00,Just another reason to stay away from coinbase...,just another reason to stay away from coinbase...,-0.3400,0.000000
280482,280482,2022-05-14 23:59:46+00:00,Another beautiful day! Please vote for $EGC ev...,another beautiful day please vote for $ egc ev...,0.7351,0.850000
280483,280483,date,tweet,tweet,0.0000,0.000000